using System.Text.Json;
using Microsoft.Extensions.Logging;
using PMS.API.Application.Services.Interfaces;
using PMS.API.Core.Domain.Entities;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using Document = QuestPDF.Fluent.Document;

namespace PMS.API.Application.Services.Implementation;

public class PdfService : IPdfService
{
  private readonly ILogger<PdfService> _logger;

  public PdfService(ILogger<PdfService> logger)
  {
    _logger = logger;
    QuestPDF.Settings.License = LicenseType.Community;
  }

  public async Task<byte[]> GenerateOrderPdfAsync(Order order)
  {
    return await Task.Run(() =>
    {
      try
      {
        var medications = ParseMedications(order.Medication ?? "");
        _logger.LogInformation("Parsed medications for Order {OrderId}: {Medications}",
          order.Id, string.Join(", ", medications ?? new List<string>()));

        var pdfBytes = Document.Create(container =>
        {
          container.Page(page =>
          {
            page.Size(PageSizes.Letter);
            page.Margin(50);

            page.Content()
              .Column(column =>
              {
                column.Item().PaddingBottom(20).Background(Colors.Grey.Lighten3)
                  .Border(1).BorderColor(Colors.Grey.Medium)
                  .Padding(10)
                  .Text(text =>
                  {
                    text.Span("Alert: ").Bold().FontSize(10).FontColor(Colors.Grey.Darken2);
                    text.Span("This is a refill order generated by a patient from our Westmount pharmacy website, this is not a prescription")
                      .FontSize(10).FontColor(Colors.Grey.Darken2);
                  });

                column.Item().AlignCenter().Text("REFILLING ORDER")
                  .FontSize(18).Bold();

                column.Item().PaddingTop(10).Text($"Order Date: {order.CreatedDate:MM/dd/yyyy HH:mm}")
                  .FontSize(9).FontColor(Colors.Grey.Medium);

                column.Item().PaddingTop(20);

                column.Item().Text("PERSONAL INFORMATION").FontSize(12).Bold();
                column.Item().PaddingTop(5);
                column.Item().Text($"First Name: {order.FirstName}").FontSize(10);
                column.Item().PaddingTop(2);
                column.Item().Text($"Last Name: {order.LastName}").FontSize(10);
                column.Item().PaddingTop(2);
                column.Item().Text($"Phone Number: {order.PhoneNumber}").FontSize(10);
                column.Item().PaddingTop(15);

                column.Item().Text("MEDICATION INFORMATION").FontSize(12).Bold();
                column.Item().PaddingTop(5);

                if (medications != null && medications.Any())
                {
                  column.Item().Text("Medications:").FontSize(10);
                  column.Item().PaddingTop(2);
                  foreach (var medication in medications)
                  {
                    if (!string.IsNullOrWhiteSpace(medication))
                    {
                      column.Item().PaddingLeft(20).Text($"• {medication}").FontSize(10);
                      column.Item().PaddingTop(2);
                    }
                  }
                }
                else
                {
                  column.Item().Text("Medication: Not specified").FontSize(10);
                }

                column.Item().PaddingTop(15);

                column.Item().Text("DELIVERY/PICKUP INFORMATION").FontSize(12).Bold();
                column.Item().PaddingTop(5);
                column.Item().Text($"Type: {order.DeliveryOrPickup}").FontSize(10);
                column.Item().PaddingTop(2);

                var isDelivery = !string.IsNullOrEmpty(order.DeliveryOrPickup) &&
                                 order.DeliveryOrPickup.Equals("Delivery", StringComparison.OrdinalIgnoreCase);

                if (isDelivery)
                {
                  if (!string.IsNullOrEmpty(order.Address))
                  {
                    column.Item().Text($"Address: {order.Address}").FontSize(10);
                    column.Item().PaddingTop(2);
                  }

                  if (!string.IsNullOrEmpty(order.DeliveryTimeSlot))
                  {
                    column.Item().Text($"Time Slot: {order.DeliveryTimeSlot}").FontSize(10);
                    column.Item().PaddingTop(2);
                  }
                }

                column.Item().PaddingTop(15);

                if (!string.IsNullOrEmpty(order.Notes))
                {
                  column.Item().Text("SPECIAL NOTES").FontSize(12).Bold();
                  column.Item().PaddingTop(5);
                  column.Item().Padding(10).Text(order.Notes).FontSize(10);
                }

                column.Item().PaddingTop(20);
                column.Item().Background(Colors.White)
                  .Border(1).BorderColor(Colors.Grey.Medium)
                  .Padding(10)
                  .Text("Please ensure you select CWR or Delivery time slot as priority (not pick up). Please call if there are any issues at all (no refills, on-order medication, backorder, clarification etc.)")
                  .FontSize(10)
                  .FontColor(Colors.Grey.Darken2);

                column.Item().PaddingTop(20);
                column.Item().AlignCenter().Text($"Order ID: #{order.Id}")
                  .FontSize(10).FontColor(Colors.Grey.Darken1).Bold();
              });
          });
        })
        .GeneratePdf();

        _logger.LogInformation("PDF generated for Order {OrderId}, size: {Size} bytes", order.Id, pdfBytes.Length);
        return pdfBytes;
      }
      catch (Exception ex)
      {
        _logger.LogError(ex, "Error generating PDF for order {OrderId}", order.Id);
        throw;
      }
    });
  }

  public async Task<byte[]> GenerateContactFormPdfAsync(
    string contactName,
    string contactLastName,
    string contactPhone,
    string contactEmail,
    string? notes)
  {
    return await Task.Run(() =>
    {
      try
      {
        var pdfBytes = Document.Create(container =>
        {
          container.Page(page =>
          {
            page.Size(PageSizes.Letter);
            page.Margin(50);

            page.Content()
              .Column(column =>
              {
                column.Item().AlignCenter().Text("CONTACT FORM SUBMISSION")
                  .FontSize(18).Bold();

                column.Item().PaddingTop(10).Text($"Submitted: {DateTime.UtcNow:MM/dd/yyyy HH:mm}")
                  .FontSize(9).FontColor(Colors.Grey.Medium);

                column.Item().PaddingTop(20);

                column.Item().Text("CONTACT INFORMATION").FontSize(12).Bold();
                column.Item().PaddingTop(5);
                column.Item().Text($"Name: {contactName}").FontSize(10);
                column.Item().PaddingTop(2);
                column.Item().Text($"Last Name: {contactLastName}").FontSize(10);
                column.Item().PaddingTop(2);
                column.Item().Text($"Phone: {contactPhone}").FontSize(10);
                column.Item().PaddingTop(2);
                column.Item().Text($"Email: {contactEmail}").FontSize(10);
                column.Item().PaddingTop(15);

                if (!string.IsNullOrWhiteSpace(notes))
                {
                  column.Item().Text("MESSAGE / NOTES").FontSize(12).Bold();
                  column.Item().PaddingTop(5);
                  column.Item().Padding(10).Text(notes).FontSize(10);
                }

                column.Item()
                  .Border(1).BorderColor(Colors.Grey.Medium)
                  .Padding(12)
                  .AlignCenter()
                  .Text("This is an internal message generated from the Westmount website patient’s contact form submission. Please read and contact the patient as soon as possible.")
                  .FontSize(14)
                  .Bold();
              });
          });
        })
        .GeneratePdf();

        _logger.LogInformation("Contact form PDF generated, size: {Size} bytes", pdfBytes.Length);
        return pdfBytes;
      }
      catch (Exception ex)
      {
        _logger.LogError(ex, "Error generating contact form PDF");
        throw;
      }
    });
  }

  public async Task<byte[]> GenerateTransferRequestPdfAsync(
    string firstName,
    string lastName,
    string phoneNumber,
    string? phoneNumber2,
    string? dateOfBirth,
    string? transferringFromPharmacy,
    string? notesOrConcerns)
  {
    return await Task.Run(() =>
    {
      try
      {
        var pdfBytes = Document.Create(container =>
        {
          container.Page(page =>
          {
            page.Size(PageSizes.Letter);
            page.Margin(50);

            page.Content()
              .Column(column =>
              {
                column.Item().AlignCenter().Text("BECOME A PATIENT / TRANSFER REQUEST")
                  .FontSize(18).Bold();

                column.Item().PaddingTop(10).Text($"Submitted: {DateTime.UtcNow:MM/dd/yyyy HH:mm}")
                  .FontSize(9).FontColor(Colors.Grey.Medium);

                column.Item().PaddingTop(20);

                column.Item().Text("PATIENT INFORMATION").FontSize(12).Bold();
                column.Item().PaddingTop(5);
                column.Item().Text($"First Name: {firstName}").FontSize(10);
                column.Item().PaddingTop(2);
                column.Item().Text($"Last Name: {lastName}").FontSize(10);
                column.Item().PaddingTop(2);
                column.Item().Text($"Phone Number: {phoneNumber}").FontSize(10);

                if (!string.IsNullOrWhiteSpace(phoneNumber2))
                {
                  column.Item().PaddingTop(2);
                  column.Item().Text($"Phone Number 2: {phoneNumber2}").FontSize(10);
                }

                if (!string.IsNullOrWhiteSpace(dateOfBirth))
                {
                  column.Item().PaddingTop(2);
                  column.Item().Text($"Date of Birth: {dateOfBirth}").FontSize(10);
                }

                column.Item().PaddingTop(15);

                if (!string.IsNullOrWhiteSpace(transferringFromPharmacy))
                {
                  column.Item().Text("TRANSFERRING FROM").FontSize(12).Bold();
                  column.Item().PaddingTop(5);
                  column.Item().Padding(10).Text(transferringFromPharmacy).FontSize(10);
                  column.Item().PaddingTop(10);
                }

                if (!string.IsNullOrWhiteSpace(notesOrConcerns))
                {
                  column.Item().Text("NOTES / CONCERNS").FontSize(12).Bold();
                  column.Item().PaddingTop(5);
                  column.Item().Padding(10).Text(notesOrConcerns).FontSize(10);
                }


                column.Item()
                  .Border(1).BorderColor(Colors.Grey.Medium)
                  .Padding(12)
                  .AlignCenter()
                  .Text("This is an internal message from Westmount website's request for a patient to transfer from another pharmacy. Please read the note, create a profile, call the patient to ask if any prescriptions are needed and call the pharmacy to request a transfer")
                  .FontSize(14)
                  .Bold();
              });
          });
        })
        .GeneratePdf();

        _logger.LogInformation("Transfer request PDF generated, size: {Size} bytes", pdfBytes.Length);
        return pdfBytes;
      }
      catch (Exception ex)
      {
        _logger.LogError(ex, "Error generating transfer request PDF");
        throw;
      }
    });
  }

  private List<string> ParseMedications(string medicationJson)
  {
    try
    {
      if (string.IsNullOrWhiteSpace(medicationJson))
      {
        return new List<string>();
      }

      var medications = JsonSerializer.Deserialize<List<string>>(medicationJson);
      if (medications != null && medications.Any())
      {
        return medications.Where(m => !string.IsNullOrWhiteSpace(m)).ToList();
      }

      var commaSeparated = medicationJson.Split(',', StringSplitOptions.RemoveEmptyEntries)
        .Select(m => m.Trim())
        .Where(m => !string.IsNullOrWhiteSpace(m))
        .ToList();

      if (commaSeparated.Any())
      {
        return commaSeparated;
      }

      return new List<string> { medicationJson.Trim() };
    }
    catch
    {
      return new List<string> { medicationJson };
    }
  }
}


